### ISSUE TITLE
OCS : cluster is in HEALTH_ERR

### ISSUE THREAD

**Issue by jtaleric** [openshift-kni/install-scripts#116]
```
Status:
  Ceph:
    Details:
      MDS_ALL_DOWN:
        Message:   1 filesystem is offline
        Severity:  HEALTH_ERR
      MDS_UP_LESS_THAN_MAX:
        Message:   1 filesystem is online with fewer MDS than max_mds
        Severity:  HEALTH_WARN
      PG_AVAILABILITY:
        Message:   Reduced data availability: 24 pgs inactive
        Severity:  HEALTH_WARN
      TOO_FEW_PGS:
        Message:      too few PGs per OSD (4 < min 30)
        Severity:     HEALTH_WARN
    Health:           HEALTH_ERR
    Last Changed:     2019-09-10T11:21:26Z
    Last Checked:     2019-09-10T16:03:56Z
    Previous Health:  HEALTH_OK
  State:              Created

```

```
NAME                                                        READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-c5nqt                                      3/3     Running     0          5h21m
csi-cephfsplugin-kn6rb                                      3/3     Running     0          5h21m
csi-cephfsplugin-lcthx                                      3/3     Running     0          5h21m
csi-cephfsplugin-provisioner-678db5bf66-bnz88               4/4     Running     0          5h21m
csi-cephfsplugin-provisioner-678db5bf66-k7dth               4/4     Running     0          5h21m
csi-rbdplugin-dg5tf                                         3/3     Running     0          5h21m
csi-rbdplugin-mf287                                         3/3     Running     0          5h21m
csi-rbdplugin-provisioner-7bf4556986-hwhsc                  5/5     Running     0          5h21m
csi-rbdplugin-provisioner-7bf4556986-qpnkp                  5/5     Running     0          5h21m
csi-rbdplugin-rjw9s                                         3/3     Running     0          5h21m
local-storage-operator-bcfd5765f-qfpfx                      1/1     Running     0          5h22m
noobaa-core-0                                               0/2     Pending     0          5h21m
noobaa-operator-6f96d69f89-89gst                            1/1     Running     0          5h22m
ocs-operator-7878485678-s29cq                               1/1     Running     0          5h22m
osd-disks-local-diskmaker-qcpgl                             1/1     Running     0          5h21m
osd-disks-local-diskmaker-r555q                             1/1     Running     0          5h21m
osd-disks-local-diskmaker-xg7f7                             1/1     Running     0          5h21m
osd-disks-local-provisioner-7c2hk                           1/1     Running     0          5h21m
osd-disks-local-provisioner-9cj8d                           1/1     Running     0          5h21m
osd-disks-local-provisioner-mc2xb                           1/1     Running     0          5h21m
rook-ceph-mds-mycluster-cephfilesystem-a-799db7669d-8w5gk   1/1     Running     0          5h17m
rook-ceph-mds-mycluster-cephfilesystem-b-6cd95bb858-j2gg2   1/1     Running     0          5h17m
rook-ceph-mgr-a-6c74697d6b-22vxb                            1/1     Running     0          5h18m
rook-ceph-mon-a-54cb68fb47-npbcr                            1/1     Running     0          5h20m
rook-ceph-mon-b-59d978bb88-xzj8n                            1/1     Running     0          5h19m
rook-ceph-mon-c-7cc66d5895-8drkp                            1/1     Running     0          5h19m
rook-ceph-operator-685695b58f-cv8gd                         1/1     Running     0          5h22m
rook-ceph-osd-0-6f784f685d-4cckt                            1/1     Running     0          5h17m
rook-ceph-osd-1-7dd4997744-mts7j                            1/1     Running     0          5h17m
rook-ceph-osd-10-5844f756f-7gxn8                            1/1     Running     0          5h17m
rook-ceph-osd-11-58b47d848b-4mv2k                           1/1     Running     0          5h17m
rook-ceph-osd-2-555c46b877-vfl4z                            1/1     Running     0          5h17m
rook-ceph-osd-3-dcd9f7549-hckcm                             1/1     Running     0          5h17m
rook-ceph-osd-4-55d9b78ff-hhvl2                             1/1     Running     0          5h17m
rook-ceph-osd-5-5c48fdbc5c-2xjml                            1/1     Running     0          5h17m
rook-ceph-osd-6-79646f956c-7sgjz                            1/1     Running     0          5h17m
rook-ceph-osd-7-767bb55984-j729p                            1/1     Running     0          5h17m
rook-ceph-osd-8-69948c56c8-vjxgd                            1/1     Running     0          5h17m
rook-ceph-osd-9-545fbcddb4-n9pd7                            1/1     Running     0          5h17m
rook-ceph-osd-prepare-osd-0-8ppjs-nkcsr                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-1-gwzl6-xlssn                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-10-xfjpd-xcx7b                    0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-11-gpjvx-g55nv                    0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-2-pb9wn-tppv8                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-3-qxx2z-kdrvs                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-4-4vnzs-9lcb2                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-5-krmwx-tz8tq                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-6-ns8gl-vcs4k                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-7-8vvwv-gj42h                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-8-74ttd-65f96                     0/1     Completed   0          5h18m
rook-ceph-osd-prepare-osd-9-cdgxm-79lfz                     0/1     Completed   0          5h18m
rook-ceph-tools-5f5dc75fd5-2rsp9                            1/1     Running     0          5h18m
```

**Comment by jtaleric** [comment]
```
sh-4.2# ceph -s
  cluster:
    id:     dcf2163a-2430-4136-91b8-a2c731bf966c
    health: HEALTH_ERR
            1 filesystem is offline
            1 filesystem is online with fewer MDS than max_mds
            Reduced data availability: 24 pgs inactive
            too few PGs per OSD (4 < min 30)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 5h)
    mgr: a(active, since 5h)
    mds: mycluster-cephfilesystem:0
    osd: 12 osds: 12 up (since 5h), 12 in (since 5h)
 
  data:
    pools:   5 pools, 40 pgs
    objects: 0 objects, 0 B
    usage:   12 GiB used, 17 TiB / 17 TiB avail
    pgs:     60.000% pgs unknown
             24 unknown
             16 active+clean
 

```
