### ISSUE TITLE
Add script to prepare bare metal nodes information

### ISSUE THREAD

**Issue by markmc** [openshift-kni/install-scripts#19]
As per https://github.com/openshift/installer/blob/master/docs/user/metal/install_ipi.md we need information like the following in `install-config.yml` with information about the bare metal nodes:

```
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://192.168.111.1:6230
          username: admin
          password: password
        bootMACAddress: 00:11:07:4e:f6:68
        hardwareProfile: default
```
